In [22]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [43]:

train_data = pd.read_csv("credit_train.csv")
test_data = pd.read_csv("credit_test.csv")

features = ['monthly_income', 'credit_sum', 'credit_month', 'score_shk', 'tariff_id']
target = 'open_account_flg'

X = train_data[features]
y = train_data[target]

X['credit_sum'] = X['credit_sum'].str.replace(',', '').astype(float)

X['score_shk'] = X['score_shk'].str.replace(',', '.').astype(float)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

<ipython-input-43-c28dfc01385a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['credit_sum'] = X['credit_sum'].str.replace(',', '').astype(float)
<ipython-input-43-c28dfc01385a>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['score_shk'] = X['score_shk'].str.replace(',', '.').astype(float)

In [44]:
train_data

,client_id,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count,open_account_flg
0,52372,M,38,MAR,SPC,"12168,00",10,1.1,"0,308454",GRD,ОБЛ ВОЛОГОДСКАЯ,25000.0,0.0,0.0,0
1,75213,F,36,MAR,SPC,"17738,00",10,1.1,"0,498147",GRD,ОБЛ БЕЛГОРОДСКАЯ,25000.0,4.0,0.0,0
2,119931,M,23,UNM,SPC,"26489,00",10,1.1,"0,431980",SCH,ЧЕЛЯБИНСКАЯ ОБЛ,25000.0,NaN,NaN,0
3,134365,M,24,UNM,SPC,"20379,00",12,1.6,"0,770546",GRD,РЕСП КАРАЧАЕВО-ЧЕРКЕССКАЯ,50000.0,NaN,NaN,1
4,138695,F,47,MAR,SPC,"12019,00",10,1.6,"0,617275",SCH,УЛЬЯНОВСКАЯ ОБЛ,18000.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136591,167442,F,55,MAR,WRP,"34732,00",6,1.1,"0,328384",UGR,АО ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - Ю,35000.0,4.0,0.0,0
136592,134582,M,30,UNM,SPC,"22990,00",7,1.6,"0,278594",SCH,ОБЛ МОСКОВСКАЯ,30000.0,1.0,0.0,0
136593,170180,F,36,DIV,SPC,"18929,00",10,1.1,"0,425852",GRD,ОМСКАЯ ОБЛАСТЬ,25000.0,0.0,0.0,0
136594,59295,F,32,MAR,UMN,"15112,80",10,1.2,"0,419264",GRD,САНКТ-ПЕТЕРБУРГ,50000.0,5.0,0.0,0
136595,167643,F,32,DIV,SPC,"33163,90",6,1.9,"0,288741",GRD,КРАЙ СТАВРОПОЛЬСКИЙ,35000.0,0.0,0.0,0

In [45]:
test_data

,client_id,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count
0,113857,F,41,UNM,BIS,"43761,60",12,1.25,"0,455897",GRD,ОБЛ САМАРСКАЯ,80000.0,4.0,0.0
1,153767,M,27,UNM,UMN,"23990,00",10,1.60,"0,491395",SCH,МОСКВА Г,64520.0,2.0,0.0
2,90278,M,40,DIV,SPC,"10439,00",12,1.10,"0,573316",SCH,ОРЛОВСКАЯ ОБЛ,30000.0,4.0,0.0
3,15138,F,31,MAR,SPC,"26589,00",10,1.10,"0,365170",GRD,ОБЛ АСТРАХАНСКАЯ,49000.0,3.0,0.0
4,8392,F,35,MAR,BIS,"97780,00",24,1.90,"0,241043",SCH,ОБЛ АСТРАХАНСКАЯ,50000.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34145,150068,M,44,DIV,SPC,"8180,85",6,1.10,"0,387485",SCH,КРАЙ ЗАБАЙКАЛЬСКИЙ,20000.0,3.0,0.0
34146,85903,M,28,MAR,SPC,"53189,00",10,1.60,"0,722263",UGR,ТАТАРСТАН РЕСП,50000.0,1.0,0.0
34147,8011,F,20,UNM,SPC,"34453,33",10,1.60,"0,661113",UGR,ТАТАРСТАН РЕСП,23000.0,NaN,NaN
34148,32173,M,23,UNM,SPC,"17430,68",12,1.60,"0,745293",SCH,КРАЙ ЗАБАЙКАЛЬСКИЙ,55000.0,NaN,NaN
34149,24712,F,48,CIV,SPC,"44430,00",12,1.50,"0,485988",SCH,ОБЛ АСТРАХАНСКАЯ,18000.0,1.0,0.0

In [46]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(len(features),)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [47]:
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_val_scaled, y_val))

Epoch 1/10
3415/3415 [==============================] - 10s 3ms/step - loss: 0.4409 - accuracy: 0.8236 - val_loss: nan - val_accuracy: 0.8220
Epoch 2/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4256 - accuracy: 0.8240 - val_loss: nan - val_accuracy: 0.8211
Epoch 3/10
3415/3415 [==============================] - 8s 2ms/step - loss: 0.4227 - accuracy: 0.8241 - val_loss: nan - val_accuracy: 0.8216
Epoch 4/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4215 - accuracy: 0.8244 - val_loss: nan - val_accuracy: 0.8174
Epoch 5/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4208 - accuracy: 0.8245 - val_loss: nan - val_accuracy: 0.8217
Epoch 6/10
3415/3415 [==============================] - 8s 2ms/step - loss: 0.4206 - accuracy: 0.8243 - val_loss: nan - val_accuracy: 0.8218
Epoch 7/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4202 - accuracy: 0.8242 - val_loss: nan - val_accuracy: 0.8213
Epoch 8/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4196 - accuracy: 0.8246 - val_loss: nan - val_accuracy: 0.8217
Epoch 9/10
3415/3415 [==============================] - 8s 2ms/step - loss: 0.4193 - accuracy: 0.8247 - val_loss: nan - val_accuracy: 0.8215
Epoch 10/10
3415/3415 [==============================] - 9s 3ms/step - loss: 0.4191 - accuracy: 0.8245 - val_loss: nan - val_accuracy: 0.8220

In [48]:
X_test = test_data[features]
X_test['credit_sum'] = X_test['credit_sum'].str.replace(',', '.').astype(float)
X_test['score_shk'] = X_test['score_shk'].str.replace(',', '.').astype(float)

X_test_scaled = scaler.transform(X_test)
predictions = model.predict(X_test_scaled)

   1/1068 [..............................] - ETA: 1:19

<ipython-input-48-2578a09172e1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['credit_sum'] = X_test['credit_sum'].str.replace(',', '.').astype(float)
<ipython-input-48-2578a09172e1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['score_shk'] = X_test['score_shk'].str.replace(',', '.').astype(float)

1068/1068 [==============================] - 2s 2ms/step

In [52]:
result = pd.DataFrame(predictions)

In [53]:
result

              0
0      0.409582
1      0.203311
2      0.438180
3      0.269580
4      0.009561
...         ...
34145  0.345482
34146  0.407368
34147  0.346464
34148  0.456980
34149  0.161550

[34150 rows x 1 columns]